services:
  emqx:
    image: emqx/emqx
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log

  frontend:
    image: ghcr.io/dliebg/schwering_app_hut/frontend:latest
    restart: unless-stopped
    ports:
      - 10007:80

  backend:
    image: ghcr.io/dliebg/schwering_app_hut/backend:latest
    restart: unless-stopped
    environment:
      - BROKER_IP=emqx
      - BROKER_PORT=1883
    env_file: .env

volumes:
  emqx-data:
  emqx-log:
